name: pib_cli Deploys

# Workflow Secrets:
# SLACK_WEBHOOK              (Required, for slack notifications...)
# DOCKER_USERNAME            (Optional, required for image pushing...)
# DOCKER_TOKEN               (Optional, required for image pushing...)

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Environment
        run: |
          echo "WEBHOOK_URL=${WEBHOOK_URL}" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${DOCKER_USERNAME}" >> $GITHUB_ENV
          echo "PROJECT_NAME=pib_cli" >> $GITHUB_ENV
          echo "USERNAME=niall-byrne" >> $GITHUB_ENV
          echo "CD_ENABLED=false" >> $GITHUB_ENV
  
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Create Docker Mounted Content
        run: |
          echo | ssh-keygen
          touch ${HOME}/.gitconfig
          touch ${HOME}/.gitconfig_global

      - name: Ensure File System is Writable by the Container
        run: |
          sudo chmod -R 777 .

      - name: Construct Image Tag
        run: |
          echo "IMAGE_NAME=${DOCKER_USERNAME}/${PROJECT_NAME}:${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # START Continuous Deployment -- Customize this Section Depending on your strategy

      - name: Is CD enabled?
        if: env.DOCKER_USERNAME != ''
        run: |
          [[ -n "${DOCKER_TOKEN}" ]] && echo "CD_ENABLED=true" >> $GITHUB_ENV
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      # Configure Docker Buildx
      - uses: docker/setup-buildx-action@v1

      # Note: This is configured for dockerhub, but this action is highly customizable
      # https://github.com/docker/login-action
      - name: Login to DockerHub
        if: env.CD_ENABLED == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Note: This is configured for dockerhub, but this action is highly customizable
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        if: env.CD_ENABLED == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./assets/Dockerfile
          push: true
          target: production
          tags: |
            ${{ env.IMAGE_NAME }}

      # END Continuous Deployment -- Customize this Section Depending on your strategy

      - name: Production -- Report Success
        if: env.CD_ENABLED == 'true'
        run: |
          ./scripts/ci/slack.sh "${PROJECT_NAME}:${GITHUB_REF#refs/tags/}" "new image has been produced and pushed!"

      - name: Production -- Report Failure
        if: failure() == true
        run: |
          ./scripts/ci/slack.sh "${PROJECT_NAME}:${GITHUB_REF#refs/tags/}" "automated image production has failed!"

